# action.yml
name: 'Push Latest Changes'
description: 'Push the latest changes from one repository to another'
author: 'steven-mi'
inputs:
  github-token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository: 
    description: 'Destination repisitory to push changes'
    required: true
  branch: 
    description: 'Branch to push changes to (default: main)'
    required: false
    default: 'main'
  force:
    description: 'Enable force push (default: false)'
    required: false
    default: false
  directory:
    description: 'Directory to push changes to (default: ".")'
    required: false
    default: '.'
  ignore:
    description: 'A list of files to be ignored as a comma-separated string (default: "")'
    required: false
    default: ''
   user_email:
    description: 'Email address to associate this commit with'
    required: false
    default: 'someone@somewhere'
   user_name:
    description: 'Name to associate this commit with'
    required: false
    default: 'someone'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}
    - ${{ inputs.force }}
    - ${{ inputs.directory }}
    - ${{ inputs.ignore }}
branding:
  icon: 'git-commit'
  color: 'green'
